### ISSUE TITLE
Javadoc completion and review for accuracy

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#103]

**Comment by xquery** [comment]
I've added commenting and regenerated javadocs. Will continue incrementally improving.

**Comment by xquery** [comment]
http://marklogic.github.io/marklogic-sesame/marklogic-sesame/build/docs/javadoc/index.html

handing off to Jane.

**Comment by xquery** [comment]
updated http://marklogic.github.io/marklogic-sesame/marklogic-sesame/build/docs/javadoc/index.html

pls confirm all is good

**Comment by jmckean17** [comment]
All is good. Thanks Jim!

**Comment by jmckean17** [comment]
How do I close this issue?

**Comment by xquery** [comment]
I've removed test label and added ship label then clicked on the button that says "close and comment" (below)
