### ISSUE TITLE
setRuleSet() method for MarkLogicRepositoryConnection class

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#104]
At this point, it looks like we don't have a way of setting default ruleset(s) for the database from within marklogic-sesame in the MarkLogicRepositoryConnection  class. Something like

public void setRulesets(SPARQLRuleset ruleset...)
public SPARQLRuleset [] getRulesets()

I assume that in the method  "public RepositoryResult<Statement> getStatements(Resource subj, URI pred, Value obj, boolean includeInferred, Resource... contexts)", when includeInferred is set to true, it applies the default rule set on the triples and returns the statements. But there doesn't seem to be a way to set default ruleset(s) as of now.

**Comment by xquery** [comment]
At the moment, one can set ruleset on the query def not the connection ... I will add some methods on connection.

**Comment by xquery** [comment]
in PR #164 which is out to review

**Comment by srinathgit** [comment]
setDefaultRulesets() method is not working. In the snippet, the code works fine with ((MarkLogicQuery)tupleQuery1).setRulesets(SPARQLRuleset.EQUIVALENT_PROPERTY);

but fails with testAdminCon.setDefaultRulesets(SPARQLRuleset.EQUIVALENT_PROPERTY); 

@Test
	public void testRuleSets1() throws Exception{
		Assert.assertEquals(0L, testAdminCon.size());
		testAdminCon.add(micah, lname, micahlname, dirgraph1);
		testAdminCon.add(micah, fname, micahfname, dirgraph1);
		testAdminCon.add(micah, developPrototypeOf, semantics, dirgraph1);
		testAdminCon.add(micah, type, sEngineer, dirgraph1);
		testAdminCon.add(micah, worksFor, ml, dirgraph1);
		testAdminCon.add(john, fname, johnfname, dirgraph1);
		testAdminCon.add(john, lname, johnlname, dirgraph1);
		testAdminCon.add(john, writeFuncSpecOf, inference, dirgraph1);
		testAdminCon.add(john, type, lEngineer, dirgraph1);
		testAdminCon.add(john, worksFor, ml, dirgraph1);
		testAdminCon.add(writeFuncSpecOf, eqProperty, design, dirgraph1);
		testAdminCon.add(developPrototypeOf, eqProperty, design, dirgraph1);
		testAdminCon.add(design, eqProperty, develop, dirgraph1);
		String query = "select  (count (?s)  as ?totalcount) where {?s ?p ?o .} ";
		TupleQuery tupleQuery1 =  testAdminCon.prepareTupleQuery(QueryLanguage.SPARQL, query);
		testAdminCon.setDefaultRulesets(SPARQLRuleset.EQUIVALENT_PROPERTY);
	//((MarkLogicQuery)tupleQuery1).setRulesets(SPARQLRuleset.EQUIVALENT_PROPERTY);
		TupleQueryResult result1 = tupleQuery1.evaluate();
		try {
			assertThat(result1, is(notNullValue()));
			assertThat(result1.hasNext(), is(equalTo(true)));
			while (result1.hasNext()) {
				BindingSet solution = result1.next();
				assertThat(solution.hasBinding("totalcount"), is(equalTo(true)));
				Value count = solution.getValue("totalcount");
				Assert.assertEquals(23,Integer.parseInt(count.stringValue()));
			}
		}
		finally {
			result1.close();
		}

**Comment by xquery** [comment]
The reason this is not working is that the code is setting the default rulesets after you prepare the querydef. If you move the 

```
testAdminCon.setDefaultRulesets(SPARQLRuleset.EQUIVALENT_PROPERTY);
```
to be set before prepareTupleQuery() then it should work.

setDefaultRulesets() should be set before any queries are prepared.

We could consider setDefaultRulesets resetting all prepared queries but Sesame has no facility to enumerate prepared queries and I have doubts that scenario is more common then just calling qdef. setRulesets on a specific query.

**Comment by srinathgit** [comment]
The test works fine after making the changes suggested.
