### ISSUE TITLE
con.clear() deletes everything except the graph document "http://marklogic.com/semantics#default-graph"

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#107]
con.clear() deletes everything except the graph document "http://marklogic.com/semantics#default-graph". All triples in the default graph are deleted but the graph document alone remains and is not deleted.  All named graph documents ARE deleted.

**Comment by xquery** [comment]
dep on java api client

**Comment by xquery** [comment]
after discussion with Charles, we agreed that this is not a bug and marking as enhancement for future discussion
