### ISSUE TITLE
Able to add, delete triples after performing con.close()

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#110]
It is expected that calling con.close() should rollback active transactions and prevent future add, delete operations by throwing RepositoryConnectionException. But I am able to add, delete triples after closing the connection The test below fails at "Assert.assertEquals(testAdminCon.size(),0);" because the size is 1 and the triple has been added. It should have ideally thrown RepositoryConnectionException at "testAdminCon.add(stmt);"

		Statement stmt = vf.createStatement(micah, homeTel, micahhomeTel, dirgraph);
		testAdminCon.begin();
		assertThat(testAdminCon.isOpen(), is(equalTo(true)));
		assertThat(testWriterCon.isOpen(), is(equalTo(true)));
		testAdminCon.add(stmt);
		testAdminCon.close();
		Assert.assertFalse(testAdminCon.hasStatement(stmt, false, dirgraph));
		testAdminCon.add(stmt);
		Assert.assertEquals(testAdminCon.size(),0);
		assertThat(testAdminCon.isOpen(), is(equalTo(false)));
		assertThat(testWriterCon.isOpen(), is(equalTo(true)));

**Comment by xquery** [comment]
Sesame should provide this functionality 'out of the box' but it looks like calling super() on the RepositoryConnection simply does not work. It does now seem to work in the new Sesame 4.0 branch ... but thats a serious rewrite (and beta) targeting Java 8. 

I am inclined to just add an isOpen field on the MarkLogicRepositoryConnection and check the state of this ... should be straightforward.

**Comment by xquery** [comment]
fix contained in PR #159

**Comment by srinathgit** [comment]
RepositoryException is thrown on all operations after con.close() is called
