### ISSUE TITLE
Ability to apply rulesets across multiple graphs

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#113]
Is it possible from sesame to apply rulesets across multiple graphs. Something similar to

xquery version "1.0-ml";
let $store := sem:ruleset-store(("equivalentClass.rules"), sem:store((), cts:collection-query(("Graph1", "Graph2"))))
let $query := ' SELECT * WHERE { ?s ?p ?o . } '
let $results := sem:sparql($query, (), (), $store)
return $results

**Comment by srinathgit** [comment]
Discrepancy between XQuery and Sesame behavior:

XQuery:

1. Insert data graph 1

xquery version "1.0-ml";
import module namespace sem = "http://marklogic.com/semantics" at "MarkLogic/semantics.xqy";

let $string :='
@prefix ad: <http://marklogicsparql.com/addressbook#> .
@prefix id:  <http://marklogicsparql.com/id#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ml: <http://marklogicsparql.com/> .


id:2222 ad:firstName "Micah" .
id:2222 ad:lastName  "Dubinko" .
id:2222 ml:writeFuncSpecOf ml:Semantics .
id:2222 ml:worksFor ml:MarkLogic .
id:2222 a ml:SeniorEngineer .

ml:LeadEngineer rdfs:subClassOf  ml:Engineer .
ml:SeniorEngineer rdfs:subClassOf  ml:Engineer .
ml:Engineer rdfs:subClassOf ml:Employee .


ml:writeFuncSpecOf rdfs:subPropertyOf ml:design .
ml:developPrototypeOf rdfs:subPropertyOf ml:design .
ml:design rdfs:subPropertyOf ml:develop .

'
let $insert := sem:rdf-insert(sem:rdf-parse($string, "turtle"), "override-graph=Graph1")
return ()

2. Insert data graph 2 

xquery version "1.0-ml";
import module namespace sem = "http://marklogic.com/semantics" at "MarkLogic/semantics.xqy";

let $string :='
@prefix ad: <http://marklogicsparql.com/addressbook#> .
@prefix id:  <http://marklogicsparql.com/id#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ml: <http://marklogicsparql.com/> .

id:1111 ad:firstName "John" .
id:1111 ad:lastName  "Snelson" .
id:1111 ml:writeFuncSpecOf ml:Inference .
id:1111 ml:worksFor ml:MarkLogic .
id:1111 a ml:LeadEngineer .

'
let $insert := sem:rdf-insert(sem:rdf-parse($string, "turtle"), "override-graph=Graph2")
return ()

3. xquery version "1.0-ml";
let $store := sem:ruleset-store(("rdfs-plus-full.rules"), sem:store((), cts:collection-query(("Graph1","Graph2"))))
let $query := '
SELECT (COUNT(*) as ?count)
WHERE
{ ?s ?p ?o . } '
let $results := sem:sparql($query, (), (), $store)
return $results

returns 374

Sesame:
The test fails at "Assert.assertEquals(374, count.stringValue());" where the count returned is 353

@Test
	public void testRuleSets2() throws Exception{
		
		testAdminCon.add(micah, lname, micahlname, dirgraph1);
		testAdminCon.add(micah, fname, micahfname, dirgraph1);
		testAdminCon.add(micah, developPrototypeOf, semantics, dirgraph1);
		testAdminCon.add(micah, type, sEngineer, dirgraph1);
		testAdminCon.add(micah, worksFor, ml, dirgraph1);
		
		testAdminCon.add(john, fname, johnfname,dirgraph);
		testAdminCon.add(john, lname, johnlname,dirgraph);
		testAdminCon.add(john, writeFuncSpecOf, inference, dirgraph);
		testAdminCon.add(john, type, lEngineer, dirgraph);
		testAdminCon.add(john, worksFor, ml, dirgraph);
		
		testAdminCon.add(writeFuncSpecOf, subProperty, design, dirgraph1);
		testAdminCon.add(developPrototypeOf, subProperty, design, dirgraph1);
		testAdminCon.add(design, subProperty, develop, dirgraph1);
		
		testAdminCon.add(lEngineer, subClass, engineer, dirgraph1);
		testAdminCon.add(sEngineer, subClass, engineer, dirgraph1);
		testAdminCon.add(engineer, subClass, employee, dirgraph1);
		
		String query = "select (count (?s)  as ?totalcount)  where {?s ?p ?o .} ";
		TupleQuery tupleQuery =  testAdminCon.prepareTupleQuery(QueryLanguage.SPARQL, query);
		((MarkLogicQuery) tupleQuery).setRulesets(SPARQLRuleset.RDFS_PLUS_FULL);
		TupleQueryResult result = tupleQuery.evaluate();
		
		try {
			assertThat(result, is(notNullValue()));
			assertThat(result.hasNext(), is(equalTo(true)));
			while (result.hasNext()) {
				BindingSet solution = result.next();
				assertThat(solution.hasBinding("totalcount"), is(equalTo(true)));
				Value count = solution.getValue("totalcount");
				Assert.assertEquals(374, count.stringValue());
			}
		}
		finally {
			result.close();
		}
}

**Comment by grechaw** [comment]
I understand this question -- from the sesame api the idea of supplying cts:collection-query above can be accomplished with a combination query.. I think we can in an example show how this kind of thing can be done.

**Comment by srinathgit** [comment]
Thanks Charles..  I think I should have phrased the issue better and shouldn't have brought the combination query into the picture.  So the issue is as follows:

There are only 2 graphs in the database (Graph1 and Graph2 with data specified in my last comment). In order apply the rulesets on the entire database, in xquery,  I run the following:

xquery version "1.0-ml";
let $store := sem:ruleset-store(("rdfs-plus-full.rules"), sem:store(()))
let $query := '
SELECT (COUNT(*) as ?count)
WHERE
{ ?s ?p ?o . } '
let $results := sem:sparql($query, (), (), $store)
return $results

The count is 374.

When I try to do the same thing from marklogic-sesame , I use the following snippet

 String query = "select (count (?s)  as ?totalcount)  where {?s ?p ?o .} ";
 TupleQuery tupleQuery =  testAdminCon.prepareTupleQuery(QueryLanguage.SPARQL, query);
 ((MarkLogicQuery) tupleQuery).setRulesets(SPARQLRuleset.RDFS_PLUS_FULL);
 TupleQueryResult result = tupleQuery.evaluate();

On iterating through the result set I see that the count is 353.

So this is the discrepancy I see.

**Comment by grechaw** [comment]
Thanks for the clarification @srinathgit , this certainly loks like an issue in its own right.

I don't think this could have anything to do with multiple graphs, but it might.  I'll label as bug, and put in verify, because I'd like to inspect better what's going on here.

**Comment by srinathgit** [comment]
There was a minor discrepancy in the data used in Sesame compared to the one in qconsole. After fixing that, I confirmed that it works as intended.
