### ISSUE TITLE
Executing a  syntactically incorrect statement within a transaction causes hang on the server side

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#118]
There is an existing bug (Issue # 106)  with hasStatement() implementation where it generates syntactically incorrect ASK statement. When such a statement is run with in a transaction, the server hangs indefinitely. If I remove the transaction, the test completes with a failure (which is expected as the hasStatement should fail). The test succeeds after removing hasStatement() .

@Test
	public void testAddDeleteInsertWhere()
		throws OpenRDFException
	{
		testAdminCon.add(fei,lname,feilname);
		testAdminCon.add(fei, email, feiemail);
		testAdminCon.begin();
		testAdminCon.prepareUpdate(
" DELETE { <" + fei.stringValue() + "> <#email> \"" + feiemail.stringValue() + "\"} "+
" INSERT { <" + fei.stringValue() + "> <#email> \"fling@marklogic.com\"} where{ ?s <#email> ?o}" ,"http://marklogicsparql.com/addressbook").execute();
Assert.assertTrue(testAdminCon.hasStatement(vf.createStatement(fei, email, vf.createLiteral("fling@marklogic.com")), false));
		testAdminCon.commit();
	}

**Comment by xquery** [comment]
in [PR #141 ](https://github.com/marklogic/marklogic-sesame/pull/141) I've added a simpler test.

```
    @Test
    public void testAddDeleteInsertWithTransaction()
            throws OpenRDFException
    {
        ValueFactory vf= conn.getValueFactory();
        conn.clear();
        URI fei = vf.createURI("http://marklogicsparql.com/id#3333");
        URI lname = vf.createURI("http://marklogicsparql.com/addressbook#lastName");
        URI email = vf.createURI("http://marklogicsparql.com/addressbook#email");
        Literal feilname = vf.createLiteral("Ling");
        Literal feiemail = vf.createLiteral("fei.ling@marklogic.com");

        conn.add(fei, lname, feilname);
        conn.add(fei, email, feiemail);
        conn.begin();
        conn.prepareUpdate("" +
                "DELETE { <http://marklogicsparql.com/id#3333> <#email> \"fei.ling@marklogic.com\"} INSERT { <http://marklogicsparql.com/id#3333> <#email> \"fling@marklogic.com\"}" +
                " where{ ?s <#email> ?o}","http://marklogicsparql.com/addressbook").execute();
        conn.commit();
        logger.info(
                "hasStatement:{}",conn.hasStatement(vf.createStatement(fei, email, vf.createLiteral("fling@marklogic.com")), false)
        );
        Assert.assertTrue("The value of email should be updated", conn.hasStatement(vf.createStatement(fei, email, vf.createLiteral("fling@marklogic.com")), false));
        Assert.assertFalse(conn.isEmpty());
    }
}
```

note that I tested placing conn.commit() before and after hasStatement assert and in both instances I observed expected behavior.

conn.commit() before - assert passes as the change is visible
conn.commit() after - assert fails as the change is not yet visible
 
Once PR has been reviewed I will merge and then assign you this bug (and label test).

**Comment by xquery** [comment]
also I note that your funct test testGetStatements() passes

**Comment by xquery** [comment]
as per my email to semantics internal ... I believe the problem is that executeAsk does not honor txid. 

the hang is due to junit interaction with @Test eg you will need to set conn.rollback() on the teardown to avoid.

following up with Sam on the fix.

**Comment by xquery** [comment]
Sam has fixed this with latest java api client... I believe this should work now ... this may fix some other bugs as well.

**Comment by srinathgit** [comment]
This will be handled using try/catch/finally block.
