### ISSUE TITLE
con.size(ctx) doesn't work

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#120]
Number of triples in a specific context is not returned using con.size(ctx) , similarily con.size(null) is not returning the number of triples that don't have a context associated.  con.size(ctx) returns the number of all the triples in db. In fact con.size(<non existent graph>) returns the number of all the triples.
"testAdminCon" is an instance of MarkLogicRepositoryConnection.java.

	testAdminCon.begin();
	testAdminCon.add(micah, lname, micahlname, dirgraph1);
	testAdminCon.add(micah, fname, micahfname, dirgraph1);
	testAdminCon.add(micah, homeTel, micahhomeTel, dirgraph1);
	testAdminCon.add(john, fname, johnfname);
	testAdminCon.add(john, lname, johnlname);
	testAdminCon.add(john, homeTel, johnhomeTel);
	Assert.assertEquals(3, testAdminCon.size(dirgraph1));
	Assert.assertEquals(6, testAdminCon.size(null));
	Assert.assertEquals(6, testAdminCon.size(vf.createURI(":asd")));
	Assert.assertEquals(0, testAdminCon.size(dirgraph));	
	Assert.assertEquals(6, testAdminCon.size());
	testAdminCon.add(dirgraph, vf.createURI("http://TYPE"), vf.createLiteral("Directory Graph"));
	testAdminCon.commit();	

The following tests that should pass , fail.
	Assert.assertEquals(3, testAdminCon.size(dirgraph1));
	Assert.assertEquals(0, testAdminCon.size(dirgraph));

The following test that should fail, pass. ":asd" is a non existent graph
	Assert.assertEquals(6, testAdminCon.size(vf.createURI(":asd")));

**Comment by grechaw** [comment]
I've verified that size(ctx) is counting more than it should.   Needs to be fixed.  Tests in place thus far miss the case there multiple contexts are in the db.

**Comment by grechaw** [comment]
It looks as though @xquery was waiting on some server functinonality to optimize size().  I'll see if that's obviously here.  I verify that the code is returning the wrong results now, but whether to fix or reimplement is the current question.

**Comment by srinathgit** [comment]
Waiting on Bug 34901

**Comment by srinathgit** [comment]
con.size(null) returns incorrect results. The query generated is "SELECT (count(?s) as ?ct) where { GRAPH ?g { ?s ?p ?o }}"

**Comment by grechaw** [comment]
I maintain that cts:size() should return SELECT (count(?s) as ?ct) where { GRAPH ?g { ?s ?p ?o }}"
but cts:size(null) should return SELECT (count(?s) as ?ct) where { GRAPH <DEFAULT_GRAPH> { ?s ?p ?o }}
Some more tricky null argument handling.  I think this is what I'd gotten started on last Friday

**Comment by xquery** [comment]
in the set of last changes @grechaw did, I was expecting con.size(null) to invoke the following query
 
```
SELECT (count(?s) as ?ct) where { GRAPH { ?s ?p ?o } filter (?g (IRI("http://marklogic.com/semantics#default-graph")))
```

unsure why the logic did not branch correctly, investigating

**Comment by xquery** [comment]
we set the expectation that null=defaultgraph

so when I run

```
    @Test
    public void testSizeAWithNullContext() throws Exception {
        Resource context5 = conn.getValueFactory().createURI("http://marklogic.com/test/context5");
        Resource nonexistent = conn.getValueFactory().createURI("http://marklogic.com/test/nonexistent");

        File inputFile1 = new File("src/test/resources/testdata/default-graph-1.ttl");
        conn.add(inputFile1, "http://example.org/example1/", RDFFormat.TURTLE, (Resource) null);

        File inputFile2 = new File("src/test/resources/testdata/default-graph-2.ttl");
        conn.add(inputFile2, "http://example.org/example1/", RDFFormat.TURTLE, context5);

        Assert.assertEquals(8, conn.size());
        Assert.assertEquals(4, conn.size(context5));
        Assert.assertEquals(4, conn.size((Resource) null));
        Assert.assertEquals(8, conn.size(context5,null));
        Assert.assertEquals(8, conn.size(null,context5));
        Assert.assertEquals(0, conn.size(nonexistent));
        conn.clear();
    }
````

I get all green ... where is the delta in Srinath's code or maybe the delta is in expectation ?

lets discuss today.

**Comment by srinathgit** [comment]
Jim,

On a more closer look, I observe the following.

The test below fails at "Assert.assertEquals("Size of default graph must be 0",0, testAdminCon.size(null));". The size returned is 6 when 0 is expected as the query generated is incorrect .( "SELECT (count(?s) as ?ct) where { GRAPH ?g { ?s ?p ?o }}" ).  

But interestingly, when I change it by casting null to Resource, the test succeeds . If the assert statement is changed to  "Assert.assertEquals("Size of default graph must be 0",0, testAdminCon.size((Resource)null));" , the test succeeds and the correct select query ("SELECT (count(?s) as ?ct) where { GRAPH ?g { ?s ?p ?o }filter (?g = (IRI("http://marklogic.com/semantics#default-graph")) )}" ) is generated.

   @Test
	public void test()
		throws Exception
	{
		try{
			testAdminCon.begin();
			testAdminCon.add(micah, lname, micahlname, dirgraph1);
			testAdminCon.add(micah, fname, micahfname, dirgraph1);
			testAdminCon.add(micah, homeTel, micahhomeTel, dirgraph1);
			
			testAdminCon.add(john, fname, johnfname,dirgraph);
			testAdminCon.add(john, lname, johnlname,dirgraph);
			testAdminCon.add(john, homeTel, johnhomeTel,dirgraph);
			
			Assert.assertEquals("Size of default graph must be 0",0, testAdminCon.size(null));
			testAdminCon.add(dirgraph, vf.createURI("http://TYPE"), vf.createLiteral("Directory Graph"));
			testAdminCon.commit();	
			
		}
		catch(Exception e){
			
		}
		finally{
			if (testAdminCon.isActive())
				testAdminCon.rollback();
		}
	}

**Comment by xquery** [comment]
out to review in PR #149

**Comment by srinathgit** [comment]
Verified that con.size() works with all combinations of inputs
