### ISSUE TITLE
No con.setGraphPermissions() or con.getGraphPermissions() in MarkLogicRepsoitoryConnection

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#122]
At this point, we don't have a method to either setGraphPermissions(context, permissions) or getGraphPermissions (context) within MarkLogicRepsoitoryConnection.java class. The only way to set permissions is through a method 'setGraphPerms' in MarkLogicUpdateQuery method.

**Comment by xquery** [comment]
sounds like a reasonable enhancement, will implement.

**Comment by srinathgit** [comment]
1. The signature of the newly implemented methods are

public void setGraphPerms(Object)
public Object getGraphPerms()

When I call getGraphPerms() , what type of object should I expect to be returned  ? Is it  'com.marklogic.client.semantics.GraphPermissions'  ? Also can't the signatures be

public void setGraphPerms(GraphPermissions)
public GraphPermissions getGraphPerms()

2.  Also shouldn't  setGraphPerms  and getGraphPerms methods have graph name  (Context) as an additional argument ?

public void setGraphPerms(Resource, GraphPermissions)
public GraphPermissions getGraphPerms(Resource)

3. I am adding two more methods to the enhancement so that it has the same methods as marklogic-jena

  public void addGraphPermissions(Resource graphName, GraphPermissions permissions);
  public void clearGraphPermissions(Resource graphName);

**Comment by xquery** [comment]
a) the signature is effectively 

public void setGraphPerms(GraphPermissions)
public GraphPermissions getGraphPerms()

They are programmed in the Sesame objects with Object and then typed in impl. I will investigate changing these (for IDE's) and update related javadocs with clear instructions.

I would suggest avoiding B) and C) ... even if Jena does this, it makes no sense to bundle up setting both graph permissions and context with a single setter/getter function. 

Please raise a separate enhancement if you would like a setContext/getContext on the RepositoryConnection object (which seems like a good thing to have) ... will comment on its behavior there.

**Comment by srinathgit** [comment]
I have created issue # 152 for setContext/getContext on the RepositoryConnection object. 
A)  If I have to obtain the permissions of a specific graph (context) say <http://abc>, how should I do it with the existing methods ?
B) Currently, if I understand correctly, getGraphPerms() returns the last set GraphPermisisons ?

**Comment by xquery** [comment]
yes that is why getGraphPerms is originally on the querydef (we might want to rename the repositoryconnection ones to imply 'default')

as for getting a named context's graph permissions, that sounds like a different enhancement.

**Comment by xquery** [comment]
PR #155 types all objects

**Comment by xquery** [comment]
setDefaultGraphPerms(GraphPermissions graph) and getDefaultGraphPerms() have been implemented

**Comment by srinathgit** [comment]
Verified that setDefaultGraphPerms(GraphPermissions graph) and getDefaultGraphPerms() have been implemented
