### ISSUE TITLE
con.setAutoCommit(false) not working

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#125]
The following snippet fails at assert condition. When autocommit is set to false, testAdminCon.begin () and testAdminCon.commit() must explicitly be called to commit a transaction (testAdminCon is an instance of MarkLogicConnectionRepository) but triple seems to be inserted to the database.

testAdminCon.setAutoCommit(false);
testAdminCon.add(micah, fname, micahfname, dirgraph1);
String query1 = "ASK WHERE {?s ?p \"Micah\" .}";
MarkLogicBooleanQuery askQuery = (MarkLogicBooleanQuery) testAdminCon.prepareBooleanQuery(QueryLanguage.SPARQL,query1);
 Assert.assertEquals(false, askQuery.evaluate());

**Comment by xquery** [comment]
setAutoCommit() was [deprecated](http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/repository/RepositoryConnection.html#setAutoCommit(boolean)) in sesame but I kept it around to understand the semantics and ensure they mapped on to what we do with ML.

setAutoCommit(false) is semantically equiv to begin() and setAutoCommit(true) equal to commit()

as per [release notes](http://rdf4j.org/sesame/2.7/docs/articles/upgrade-notes.docbook?view)) pls retest using begin() and commit().

**Comment by srinathgit** [comment]
I already have tests for begin() and commit() and hence will remove this test

**Comment by srinathgit** [comment]
Closing the case as the con.setAutoCommit(boolean) has been deprecated and tests using begin and commit () are in place.
