### ISSUE TITLE
Should the context be null or http://marklogic.com/semantics#default-graph

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#129]
I am inserting triple to default graph using add() method. I return all the triples which don't have a context associated with it with testAdminCon.getStatements(null, null, null, false, null). The returned triple have a context "http://marklogic.com/semantics#default-graph" which is our default graph. Should this be http://marklogic.com/semantics#default-graph or should we return a null ?

testAdminCon.add(john, fname, johnfname);
RepositoryResult<Statement> result = testAdminCon.getStatements(null, null, null, false, null);
		try {
			while (result.hasNext()) {
				Statement st = result.next();
				System.out.println(st.getContext().stringValue());
		}
		}
		finally {
			result.close();
		}

**Comment by grechaw** [comment]
I think it should be a null.  I'll take off 'question' and make this a bug.

**Comment by grechaw** [comment]
I've fixed this now.  context will be null for 'default graph'

**Comment by srinathgit** [comment]
Verified that context is null for 'default graph'. Shipping it now.
