### ISSUE TITLE
con.remove(Iterable, Resource) not working

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#130]
The below snippet fails at testAdminCon.remove(iterable1, dirgraph); which is not expected.

 "{"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"REST-INVALIDPARAM", "message":"REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Search query parameters not supported for SPARQL update: pageLength"}}"

testAdminCon.add(john,fname, johnfname);
Statement st1 = vf.createStatement(fei, fname, feifname,dirgraph);
Statement st2 = vf.createStatement(fei, lname, feilname, dirgraph);
Statement st3 = vf.createStatement(fei, email, feiemail, dirgraph);

StatementList<Statement> sL = new StatementList<Statement>(st1);
sL.add(st2);
sL.add(st3);
StatementIterator iter = new StatementIterator(sL);
Iterable<? extends Statement>  iterable = new StatementIterable(iter);
	
testAdminCon.add(iterable);
Assert.assertEquals(4L,testAdminCon.size());

StatementList<Statement> sL1 = new StatementList<Statement>(st1);
sL1.add(st2);
sL1.add(st3);
StatementIterator iter1 = new StatementIterator(sL1);
Iterable<? extends Statement>  iterable1 = new StatementIterable(iter1);
Assert.assertTrue(iterable1.iterator().hasNext());

testAdminCon.remove(iterable1, dirgraph);
Assert.assertEquals(1L,testAdminCon.size());

**Comment by grechaw** [comment]
I believe this is fixed now.

**Comment by srinathgit** [comment]
Verified that the fix works. Shipping the bug now
