### ISSUE TITLE
Adding a Language Literal

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#131]
This issue is opened for adding language tags to literal.

Literal languageLiteral = vf.createLiteral("the number four", "en");
testAdminCon.add(micah, homeTel, languageLiteral,dirgraph);

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at /graphs/sparql: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Bind variable type parameter requires XSD type

**Comment by grechaw** [comment]
This behavior is expected.  Your second test is interpreted as an invalid datatype though, not an invalid language.  I've seen languages elsewhere in the sesame code... they don't look like this I think.

Literal invalidLanguageLiteral = vf.createLiteral("the number four", "japanese");
testAdminCon.add(micah, homeTel, invalidLanguageLiteral,dirgraph);

**Comment by srinathgit** [comment]
Charles,
Will this test be correct for adding invalid language literal ? Also can you confirm if this has to fail with "com.marklogic.client.FailedRequestException" .

Literal invalidLanguageLiteral = vf.createLiteral("the number four", "en_us");
testAdminCon.add(micah, homeTel, invalidLanguageLiteral,dirgraph);

**Comment by grechaw** [comment]
Looking at the code, I do not see how we could be supporting language strings properly from the Java Client API.  There may be a gap.

**Comment by grechaw** [comment]
Indeed, our support for language literals is not exposed for bindings in the Java layer.  I'll make an issue for it in Java Client API.

**Comment by grechaw** [comment]
The Java API does support binding language strings.

 public SPARQLBindings bind(String name, String value);
 public SPARQLBindings bind(String name, String value, String datatype);
 public SPARQLBindings bind(String name, String value, Locale languageTag);

So you have found a bug, but not the one you were looking for originally.

**Comment by xquery** [comment]
yes I believe Sam added this some time ago ... looks straightforward claiming

**Comment by xquery** [comment]
ok I have addressed the proper setting of language tags with PR #167.

Any additional exception handling will be addressed by #73.

**Comment by srinathgit** [comment]
Verified that we are able to add language tag to literals from marklogic-sesame
