### ISSUE TITLE
Incorrect behavior observed with con.remove(Statement)

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#132]
The snippet below fails at the assert. There is no triple equivalent to st1 in the db but the triple "john, fname, johnfname" is getting removed which is not expected.

testAdminCon.begin();
testAdminCon.add(john, lname, johnlname, dirgraph);
testAdminCon.add(john, fname, johnfname, dirgraph);
testAdminCon.commit();

Statement st1 = vf.createStatement(john, fname, johnlname);
testAdminCon.remove(st1);
Assert.assertEquals("There is no triple st1 in the repository, so it shouldn't be deleted",2L, testAdminCon.size());

**Comment by grechaw** [comment]
Verified.  This is a bug with binding variables in the object position.

**Comment by grechaw** [comment]
Fixed in my branch.

**Comment by grechaw** [comment]
@srinathgit  I just pushed a bunch of commits to marklogic/develop.  (Actually did it prematurely, I had not meant to).    I think that I've fixed several issues in here-- I'm going to see what I can set to test, but if I've made a mistake just send it back please.

**Comment by srinathgit** [comment]
The fix works. Shipping the bug.
