### ISSUE TITLE
Should uncommited updates be visible to the own connection ?

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#133]
The below snippet fails at "assertTrue("Uncommitted update should be visible to own connection",
testAdminCon.hasStatement(john, email, johnemail, false, dirgraph)); . Is this expected ? I thought within the transaction, uncommited updates are visible to own connection.

testAdminCon.begin();
testAdminCon.add(john, email, johnemail,dirgraph);

assertTrue("Uncommitted update should be visible to own connection",
		testAdminCon.hasStatement(john, email, johnemail, false, dirgraph));
assertFalse("Uncommitted update should only be visible to own connection",
		testReaderCon.hasStatement(john, email, johnemail, false, dirgraph));
assertThat(testWriterCon.size(), is(equalTo(0L)));

testAdminCon.commit();

**Comment by grechaw** [comment]
The uncommitted update should be visible yes.

**Comment by xquery** [comment]
yes I agree with Charles, pls track with #118 (and #106) there is a bug in java api client ... passing this back to you to test when those bugs get cleared

**Comment by gvaidees** [comment]
What is to be tested with this? This seems more like a question. Should this be closed? And I agree with Charles.

**Comment by srinathgit** [comment]
@gvaidees ,

The original issue was that uncommitted updates were not visible to the own connection. This was due to a bug in java api client layer  issue #357 . So, I think it should be marked as a bug and will ship it after testing it.

**Comment by srinathgit** [comment]
Uncommitted updates are visible to own connection

**Comment by srinathgit** [comment]
I just saw that the following test fails at Assert. 

@Test
	public void testAddRemoveInsert()
		throws OpenRDFException
	{
		Statement stmt = vf.createStatement(micah, homeTel, micahhomeTel);
		testAdminCon.add(stmt);
		try{
			testAdminCon.begin();
			testAdminCon.remove(stmt);
			Assert.assertEquals("The size of repository must be zero",0, testAdminCon.size());
}

**Comment by xquery** [comment]
ok I will assume you mean with latest ML b8_0, will rebuild there and see if I can discover what is happening.

**Comment by xquery** [comment]
nice test ... adding a variant to unit tests ... fixed

**Comment by srinathgit** [comment]
The test succeeds now.
