### ISSUE TITLE
update java api client dep in gradle

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#137]
when there is an official release of java api client will need to switch build.gradle to use minted maven version of java api client (instead of locally built snapshot).

**Comment by gvaidees** [comment]
Please assign a milestone and also status (new, verify etc.) and severity (major, minor) etc.

**Comment by gvaidees** [comment]
Why does this not have a status (new, verify etc.) and severity (major, minor)? I understand this is a release task. But, if we are tracking this, we need to make sure they are reflected in the issue

**Comment by xquery** [comment]
Ganesh, I believe I am experiencing issues with github/bugtrack integration .. several times I have set required fields in bugtrack only to find that the changes have not been saved ... maybe their is a sync issue with github/bugtrack integration .. resetting.

**Comment by srinathgit** [comment]
Verified that java client api version has been changed
