### ISSUE TITLE
refactor size() to leverage aggregate fixes

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#139]
recent work in the server means we have opportunity to refactor size() to use COUNT which should be both much faster (and correct).

**Comment by grechaw** [comment]
I think this has been done.  What more needs doing in here do you think?

**Comment by xquery** [comment]
nothing needs doing ... just tidying up

**Comment by gvaidees** [comment]
Please assign a milestone.

**Comment by gvaidees** [comment]
Jim,

This is in Test without a milestone? Can you assign one

**Comment by xquery** [comment]
I keep on trying ... will try again ....

**Comment by xquery** [comment]
this is verified in several places, originally this should have been marked as a task .. .closing
