### ISSUE TITLE
setConstrainingQueryDefinition() and getConstrainingQueryDefinition() methods not available for MarkLogicRepositoryConnection class

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#142]
setConstrainingQueryDefinition() and getConstrainingQueryDefinition() methods not available for MarkLogicRepositoryConnection class. They are available currently in 'MArkLogicQuery' class

**Comment by xquery** [comment]
note that I have fix in another branch as it conflicts with other pending PR's, will merge once all PR's have been reviewed.

**Comment by xquery** [comment]
now merged, pls test

**Comment by srinathgit** [comment]
The methods don't work (Please check test testStructuredQuery). The code fails at assert which is not expected. Upon uncommenting the line "askQuery1.setConstrainingQueryDefinition(structuredDef);", it works fine. 

 StructuredQueryBuilder qb = new StructuredQueryBuilder();
  QueryDefinition structuredDef = qb.build(qb.term("Second"));
MarkLogicBooleanQuery askQuery1 = (MarkLogicBooleanQuery) testAdminCon.prepareBooleanQuery(QueryLanguage.SPARQL,negQuery);
testAdminCon.setDefaultQueryDef(structuredDef);
//askQuery1.setConstrainingQueryDefinition(structuredDef);
Assert.assertEquals(false, askQuery1.evaluate());


Similarily,  the following fails at assert as qd.getOptionsName()  returns null

QueryDefinition qd = testAdminCon.getDefaultQueryDef();
Assert.assertEquals("Second",qd.getOptionsName() );

**Comment by xquery** [comment]
this issue is similar to #104 eg. move 

```
testAdminCon.setDefaultQueryDef(structuredDef);
```

to set Constraining query before you instantiate a query object.

**Comment by srinathgit** [comment]
The first issue is resolved . The second issue mentioned still exists. The first assert fails because the string returned is "null" and second assert fails because qd.getOptionsName() throws a NullPointerException

     QueryDefinition qd = testAdminCon.getDefaultQueryDef();
     Assert.assertEquals("Second",qd.getOptionsName() );
     
     testAdminCon.setDefaultQueryDef(null);
     qd = testAdminCon.getDefaultQueryDef();
     Assert.assertEquals("null",qd.getOptionsName() );

**Comment by xquery** [comment]
this is correct behavior ... you would have needed to set option name on the QueryDefinition.

for example;

```
        qd.setOptionsName("test");
```

any subsequent calls on qd.getOptionsName() should return string value "test".

please send this back to me if I am missing something.

**Comment by srinathgit** [comment]
Shipping the bug as the reported behavior seems intended. The tests have been modified accordingly.
