### ISSUE TITLE
con.hasStatement(st, null) generates incorrect ASK query

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#153]
The following test fails at  "Assert.assertFalse(testWriterCon.hasStatement(st1, false, null));" as the ASK query generated is incorrect.  The test 	"Assert.assertFalse(testWriterCon.hasStatement(st1, false, (Resource)null));" works fine though.

public void testPrepareGraphQuery3() throws Exception
{
	Statement st1 = vf.createStatement(john, fname, johnfname, dirgraph);
	testWriterCon.add(st1);
	Assert.assertTrue(testWriterCon.hasStatement(st1, false));
	Assert.assertFalse(testWriterCon.hasStatement(st1, false, (Resource)null));
	Assert.assertFalse(testWriterCon.hasStatement(st1, false, null));
}

**Comment by grechaw** [comment]
OK

**Comment by xquery** [comment]
enhanced logic to handle a single vararg of value null in hasStatement ... fix is in PR #154 waiting for review

**Comment by srinathgit** [comment]
Verified that hasStatement  works fine
