### ISSUE TITLE
Uncommitted  updates visible to other connections

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#183]
In the snippet below, the test fails at "assertThat(testWriterCon.size(), is(equalTo(0L)));", the size returned is 1 and not 0 which is not expected.

	public void testSizeCommit()
		throws Exception
	{
		testAdminCon.setIsolationLevel(IsolationLevels.SNAPSHOT);
		assertThat(testAdminCon.size(), is(equalTo(0L)));
		assertThat(testWriterCon.size(), is(equalTo(0L)));
		try{
			testAdminCon.begin();
			testAdminCon.add(john, fname, johnfname,dirgraph);
			assertThat(testAdminCon.size(), is(equalTo(1L)));
			assertThat(testWriterCon.size(), is(equalTo(0L)));
			testAdminCon.add(john, fname, feifname);
			assertThat(testAdminCon.size(), is(equalTo(2L)));
			assertThat(testWriterCon.size(), is(equalTo(0L)));
			testAdminCon.commit();
		}
		catch (Exception e){
			
		}
		finally{
			if (testAdminCon.isActive())
				testAdminCon.rollback();
			
		}
		assertThat(testAdminCon.size(), is(equalTo(2L)));
		assertThat(testWriterCon.size(), is(equalTo(2L)));
	}

**Comment by xquery** [comment]
yes I can now replicate the problem, can we now close #51 ?

**Comment by xquery** [comment]
ok I can confirm that this is due to me including codepath that takes advantage of mergeGraphs supporting txid ... which is not yet supported in java api client. I will follow up with Sam on status of this.

**Comment by xquery** [comment]
PR #196 is done and being reviewed

**Comment by xquery** [comment]
this fix is dep on latest 3.0-develop java api client

**Comment by srinathgit** [comment]
The tests run fine after the fix
