### ISSUE TITLE
Ability to add multiple value for a binding

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#198]
In the following SPARQL query, multiple values for ?firstname can be provided. But from within Sesame, we can add only one value using query.setBinding("firstname", vf.createLiteral("Micah")); . This is an enhancement request for the ability to add multiple values for a variable. If we can already do it, please let me know and close this request.

PREFIX ad: <http://marklogicsparql.com/addressbook#> 
SELECT ?person ?firstname ?lastname ?phonenumber 
FROM <http://marklogic.com/dirgraph> 
WHERE {    
?person <#firstName> ?firstname ;           
            <#lastName> ?lastname.    
OPTIONAL {?person <#homeTel> ?phonenumber .}    
VALUES ?firstname { "Micah" "Fei" } }  
ORDER BY ?lastname

**Comment by xquery** [comment]
This functionality was addressed in the recent 4.0 release of Sesame (targeting java 8) but this is not possible in Sesame 2.8.

https://openrdf.atlassian.net/browse/SES-1021

closing.
