### ISSUE TITLE
track against Sesame 2.8.7 

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#218]
assess bumping deps to Sesame 2.8.7 before release

**Comment by xquery** [comment]
verified this works with 2.8.7

**Comment by xquery** [comment]
as we have verified it works, will close the issue.

**Comment by xquery** [comment]
change notices

**Comment by xquery** [comment]
nothing special required to verify, just build/test marklogic-sesame

**Comment by xquery** [comment]
should probably add a note in the README about supporting Sesame 2.8.7

**Comment by gvaidees** [comment]
Can this be closed? If so, make sure to clear assignee and change label from Test to ship

**Comment by srinathgit** [comment]
Shipping the bug
