### ISSUE TITLE
SPARQL CONSTRUCT query returning no statements results in error

### ISSUE THREAD

**Issue by robert-david** [marklogic/marklogic-sesame#230]
Get a repository connection of a MarkLogicRepository. Execute a SPARQL CONSTRUCT query that returns no statements. When calling the hasNext() method of the result set an error occurs.

[ERROR] ParseErrorLogger [Rio fatal] Expected '<' or '_', found: { (1, -1)

**Comment by xquery** [comment]
adding a unit test that explicitly tests this condition which runs correctly (w/ empty db or db with triples in it).

```
    @Test
    public void testGraphQueryWithConstructThatReturnsNoResults()
            throws Exception {
        String queryString = "PREFIX nn: <http://semanticbible.org/ns/2006/NTNames#>\n" +
                "PREFIX test: <http://marklogic.com#test>\n" +
                "construct { ?s  test:test \"0\"} WHERE  {?s nn:nonexistent nn:nonexistent . }";
        GraphQuery graphQuery = conn.prepareGraphQuery(QueryLanguage.SPARQL, queryString);
        GraphQueryResult results = graphQuery.evaluate();
        Assert.assertFalse(results.hasNext());
     }
```

can you provide any more information ?

**Comment by srinathgit** [comment]
This seems to be same as issue 44. I had added a test,'testPrepareGraphQuery3()' where a DESCRIBE  query returns an empty result set. I don't see that test failing but I do see the following in the wire trace 

"10:24:30.162 [pool-2-thread-2] ERROR o.o.r.h.ParseErrorLogger - [Rio fatal] Expected '<' or '_', found: { (1, -1)"

**Comment by xquery** [comment]
might be, though ParseErrorLogger is quite common response to a lot of different things.

Can you confirm the pool-2-thread-2 Error is part of the test (and not the setup).

I think its worth raising a new issue specifically for this.

**Comment by srinathgit** [comment]
I am not sure if I understand what you mean by "pool-2-thread-2 Error is part of the test" . My understanding is it is the name of the executing thread . My test has only the 'main' thread.

**Comment by grechaw** [comment]
There is an underlying bug in the server that causes this issue.
If I'm correct, @xquery , then marklogic-sesame uses the accept header "application/json" for query results.  If instead, the CONSTRUCT query always sends accept: application/ntriples, then I think you'll avoid this error.  

In any event (again, if this traces to server bug) its to be fixed in 8.0-5 , and I think there are workarounds to be done now.

**Comment by xquery** [comment]
thanks Charles that probably explains why I was not replicating (was using latest b8 but was not aware of that bug).

**Comment by xquery** [comment]
@grechaw this passes now in latest b8 ... did you fix this ?

**Comment by xquery** [comment]
@grechaw will this fix find its way into server ML 8.0-4-2 ?

**Comment by grechaw** [comment]
No, it's dependent on a server bug slated for 8.0-5.

**Comment by xquery** [comment]
to verify - test with 8.0-5 (when minted) or test with current b8.

**Comment by srinathgit** [comment]
Verified that result.hasNext() on an empty result set from CONSTRUCT query no longer throws error
