### ISSUE TITLE
MarkLogicRepositoryConnection set isolation level 

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#252]
communicated to me via email:

The basic issue is that the MarkLogicRepositoryConnection does set the isolation level in its constructor. This works fine in most cases, but in the case where a new MarkLogicRepositoryConnection is created during an ongoing transaction the RepositoryConnectionBase class (openrdf) then throws an exception. Actually the isolation level does not even change since the MarkLogicRepositoryConnection is always setting it to IsolationLevels.SNAPSHOT and the MarkLogicRepositoryConnection.setIsolationLevel(IsolationLevel level) method does not allow for any other levels. So you are basically not changing the level at all, but still the exception is thrown since there is no check in place in MarkLogicRepositoryConnection before passing it on to the RepositoryConnectionBase to see if the new level is actually a different one.

Example:

void main() {
    RepositoryConnection conn = FACTORY.getRepository().getMarkLogicConnection();
    conn.begin();
    doSomeStuff();
    conn.commit();
}

void doSomeStuff() {
    RepositoryConnection anotherConn = FACTORY.getRepository().getMarkLogicConnection();
   //exception
}  

We know we could work around this issue by passing on the first connection object instead of creating a second one. But in our use case it is not really practical or feasible to pass on the object through the entire call hierarchy. All other stores we are using (like Virtuoso and Sesame) are fine with opening new repository connections within transactions, only yours is throwing an exception. 

Versions:
openrdf-sesame-2.8.9
marklogic-sesame-1.0.0

**Comment by xquery** [comment]
I have removed the setting of isolation level.

**Comment by srinathgit** [comment]
Added test testIsolationLevel() to the suite. The issue no longer occurs
