### ISSUE TITLE
close GraphQueryResult throws NPE in functional test suite

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#257]
testPrepareGraphQuery3 in functional tests throwing a NPE when trying to close iterator.

```
result.close()
```
when the result is null, which means we should do this

```
        if(result != null) {result.close();}
```

this behavior is defined by Sesame.

Srinath I propose we amend offending test in functional test suite.

**Comment by srinathgit** [comment]
NPE is no longer thrown.
