### ISSUE TITLE
A number of unit tests are failing

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#263]
There are a number of unit tests in marklogic-sesame project that are currently failing though all the functional tests pass. It seems like most of the failures are because of some issues with the test setup.

**Comment by xquery** [comment]
all func and unit tests pass for me - I am a little unclear what this bug is assigned to me - are you referring to the jenkins job ?

**Comment by xquery** [comment]
@kkanthet confirms this issue was due to using 8.0-5 server pkg from production and there is an extra step that is needed to bring the server  up. Passing back to @srinathgit

**Comment by srinathgit** [comment]
Unit tests run fine after making sure setup runs fine.
