### ISSUE TITLE
concurrent update queries cause intermittent MarkLogicTransactionExceptions

### ISSUE THREAD

**Issue by jteh** [marklogic/marklogic-sesame#282]
MarkLogic Sesame 1.0.1 is being used in a REST web service in Tomcat to ingest/retrieve RDF. load tests with concurrent users reveal intermittent exceptions such as 

com.marklogic.semantics.sesame.MarkLogicTransactionException: No active transaction to commit.
or 
[multithreaded-sesame-test.tar.gz](https://github.com/marklogic/marklogic-sesame/files/400492/multithreaded-sesame-test.tar.gz)

com.marklogic.client.FailedRequestException: Local message: transaction commit failed: Bad Request. Server Message: XDMP-NOTXN: xdmp:xa-complete1(xs:unsignedLong(&quot;15996766929729096764&quot;), xs:unsignedLong(&quot;18239877476158707040&quot;), fn:true()) -- No transaction with identifier 18239877476158707040
or
javax.servlet.ServletException: java.lang.RuntimeException: org.openrdf.query.QueryEvaluationException: Local message: failed to apply resource at /graphs/sparql: Internal Server Error. Server Message: Transaction with identifier 12160542440929064190 already completed 

Attached is a JUnit test performing concurrent ingestion using the ML Sesame api with multiple threads that reproduces the exceptions seen on deployed REST web service. They result in 500 responses to clients of the webservice but in the test case are just printed to console as thread exceptions do not propagate up to the main thread.

From taking a peek into the ML sesame code, it appears as if com.marklogic.semantics.sesame.MarkLogicRepository creates a single instance of MarkLogicClient on instantiation that is shared across multiple MarkLogicRepositoryConnections (constructed in MarkLogicRepository.getConnection() for each thread/request). Storing the client as a field in this case might lead to threading issues as the single client is effectively being shared across thread instances (requests in the deployed webservice). I notice the single client also stores the transaction in a field on itself which is also prone to threading issues.

**Comment by xquery** [comment]
I thought we fixed this in 1.0.1 ... will investigate and thank you for the detailed bug report - it really helps.

**Comment by xquery** [comment]
minimal patch in place ... we have delayed any work on sesame during 9 but I have tested this with the very useful test @jteh supplied.

over to QA for test/release

**Comment by srinathgit** [comment]
Verified the fix works and all the existing tests run fine

**Comment by xquery** [comment]
adding this link for reference:

http://rdf4j.org/doc/programming-with-rdf4j/the-repository-api/#Multithreaded_Repository_Access
