### ISSUE TITLE
testOpen in com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#295]
the last assert() in testOpen should fail, test needs to be amended.

**Comment by xquery** [comment]
also need to add result.close() to any TupleQuery tests

**Comment by xquery** [comment]
after your recent commits this no longer is failing, can you verify ?

**Comment by srinathgit** [comment]
The test runs fine after the recent commit.
