### ISSUE TITLE
refactor write cache to use INSERT DATA

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#321]
as per internal discussions, decision is to refactor write cache to use INSERT DATA instead of merge graphs.

some background information on server locking behavior from @ariesli: 

> For WITH <graph> DELETE/INSERT, exclusive write lock on a synthetic uri of the graph in the WITH clause(not the graph uri itself) and the document uris you are inserting or deleting on.
> 
> For INSERT DATA, DELETE DATA, exclusive write lock on the document uris you are inserting or deleting on.

**Comment by xquery** [comment]
ensure permissions are set properly

**Comment by xquery** [comment]
ready for testing

**Comment by srinathgit** [comment]
Verified that tests are running fine
