### ISSUE TITLE
research RDF4J migration ?

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#322]
Adhoc sampling of customers and users of 2.# Sesame branch points towards migration to RDF4J in 12-16 mth time period.

We should investigate what it will take to refactor existing MarkLogicRepository to new eclipse project.

http://rdf4j.org/

**Comment by xquery** [comment]
assigning @sbuxton to provide guidance

**Comment by lawrence-pressinnov** [comment]
hey, 
wondering if there has been any updates on this, really interested to follow up.

**Comment by xquery** [comment]
we are having internal discussions on this - will update this thread once we get a plan in place.

**Comment by sbuxton** [comment]
Looks like this is something we need to do, now looking into resources and scheduling.
If you have a pressing use case please post here (or send to me at stephen dot buxton at marklogic dot com) to influence the priority.
Thanks.

**Comment by grechaw** [comment]
I'll be taking Jim's work on scoping this project, seeing if I can map it in my head, and will work with Akshay to see whether it's something he can tackle.  Our next meeting is Monday morning; I expect to start looking more deeply at rdf4j myself early next week.

**Comment by grechaw** [comment]
In progress and managed in marklogic-rdf4j project.
