### ISSUE TITLE
StructuredQuery options name not passed to SPARQLQueryDefinition

### ISSUE THREAD

**Issue by bsdang** [marklogic/marklogic-sesame#326]
When passing a structured query to scope the sparql query, the name of the options is not passed onto the SPARQLQueryDefinition, because of which the structured query is not applied.

**Comment by grechaw** [comment]
I think this same bug is in the jena codebase.  @bsdang you're really our first customer for any of this constraining query + SPARQL code so many appreciations for giving it a whirl!

I'll find the sesame test case and make a task over in jena depending on what i observe.

**Comment by srinathgit** [comment]
Verified that the fix works. Shipping the bug
