### ISSUE TITLE
Passing through other QueryDefinition methods to SPARQLQueryDefintion

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#334]
In addition to the setOptionsName addressed in #326, other methods in QueryDefinition  have to be passed to SPARQLQueryDefintion

**Comment by xquery** [comment]
in addition to the work @bsdang did I have set the following:

* qdef.setDirectory
* qdef.setCollections
* qdef.setResponseTransform

though it makes me wonder why the java api client does not to set all these (and setOptionsName) when stting the constraining query in the first instance, et al: 

```
qdef.setConstrainingQueryDefinition(getConstrainingQueryDefinition());
```
