### ISSUE TITLE
Make transaction accessible from com.marklogic.semantics.sesame.MarkLogicRepositoryConnection

### ISSUE THREAD

**Issue by jteh** [marklogic/marklogic-sesame#358]
It would be useful to have com.marklogic.client.Transaction accessible from an instance of com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.

Access to the current transaction is desirable in the case where a multi model (ie document and rdf) approach is being adopted. e.g. desire to persist both triple data via RDF and perform document based operations (lik, writing XML documents, tagging documents with collections) all as part of the same transaction.

The Transaction of a MarkLogicRepositoryConnection can be found at

MarkLogicRepositoryConnection.getMarkLogicClient().tx

however both getMarkLogicClient() and the tx field are private in their enclosing classes.

**Comment by xquery** [comment]
sounds like a reasonable feature ... we may even want the ability to pass a java api client transaction object as well.

**Comment by grechaw** [comment]
This issue was implemented in rdf4j project.    I'll close this issue and refer to rdf4j for further info.  We track issues for that project internally.  See https://github.com/marklogic/marklogic-rdf4j/commit/7b7e3a86d11c49511da55d21a8e056d2bd75c033
