### ISSUE TITLE
"Export statements" with multiple contexts exports no data

### ISSUE THREAD

**Issue by elky87** [marklogic/marklogic-sesame#360]
Assume you have the following data structure

subj1 pred1 obj1 < context1>
subj2 pred2 obj2 < context2>
subj3 pred3 obj3 < context3>

If I want to export all the triples from context1 and context2 I use the following method:

marklogicConnection.export(null, null, null, true, context1, context2)

From the rdf4j javadoc: http://docs.rdf4j.org/javadoc/latest/

// Ex 1: this method retrieves all statements that appear in either context1 or
 // context2, or both.
 RepositoryConnection.getStatements(null, null, null, true, context1, context2);

and

"Exports all statements with a specific subject, predicate and/or object from the repository, optionally from the specified contexts."

In the current implementation you get no results at all because the query for retrieving the statements is built as follows: 

select ?s ?p ?o WHERE {
GRAPH < context1 > {?s ?p ?o .} 
GRAPH < context2 > {?s ?p ?o .} 
}

So we only get triples that are in both context1 AND context2 which is a bug.

Fix it by changing the query to 

select ?s ?p ?o WHERE {
{GRAPH < context1 > {?s ?p ?o .} } UNION
{GRAPH < context2 > {?s ?p ?o .} }
}

**Comment by grechaw** [comment]
Hi @elky87 , this issue's fix has been merged into the rdf4j develop branch. Thanks for your help getting it reported and addressed. I'll close this one out as part of our cleanup of this repository.
We don't intend to fix this bug in the marklogic-sesame project.
