### ISSUE TITLE
"export statements" graph information gets lost

### ISSUE THREAD

**Issue by elky87** [marklogic/marklogic-sesame#361]
When using markLogicConnection.export() the graph information for the exported statements gets lost.

Assume the following data structure

subj1 pred1 obj1 < context1>
subj2 pred2 obj2 < context2>
subj3 pred3 obj3 < context3>

If we use .export(null, null, null, false, context1 ,context2) the result will be
subj1 pred1 obj1
subj2 pred2 obj2

without the context information

**Comment by elky87** [comment]
as a solution for this issue and also for https://github.com/marklogic/marklogic-sesame/issues/360 I pushed code that re-uses getStatements() which works correct.

**Comment by grechaw** [comment]
Thank you @elky87 , we'll have motion on this issue with the other ones next week.

**Comment by grechaw** [comment]
Hi @elky87 , this issue's fix has been merged into the rdf4j develop branch.  Thanks for your help getting it reported and addressed.  I'll close this one out as part of our cleanup of this repository.
We don't intend to fix this bug in the marklogic-sesame project.
