### ISSUE TITLE
Add statements/remove statements method should ignore context of statement if other contexts are supplied

### ISSUE THREAD

**Issue by elky87** [marklogic/marklogic-sesame#362]
Assume the following statement:

statement1 = subj1 pred1 object1 < context1>

if I add this statement to my Repository via

 marklogicConnection.add(statement1, context2)

I want the following data inside my repository

subj1 pred1 object1 < context2>

but right now I get this result
subj1 pred1 object1 < context1>
subj1 pred1 object1 < context2>

see also latest javadoc: http://docs.rdf4j.org/javadoc/latest/

// Ex 5: this method adds a statement to context1 in the store. It completely
 // ignores any context the statement itself has.
 RepositoryConnection.add(statement, context1);

same applies to remove, see also javadoc:
"Removes the supplied statements from a specific context in this repository, ignoring any context information carried by the statements themselves"

**Comment by grechaw** [comment]
Thanks for the bug report and the fix @elky87

**Comment by grechaw** [comment]
Hi @elky87 , this issue's fix has been merged into the rdf4j develop branch. Thanks for your help getting it reported and addressed. I'll close this one out as part of our cleanup of this repository.
We don't intend to fix this bug in the marklogic-sesame project.
