### ISSUE TITLE
Remove statements with multiple contexts does not delete statements

### ISSUE THREAD

**Issue by elky87** [marklogic/marklogic-sesame#363]
This is basically the same issue as https://github.com/marklogic/marklogic-sesame/issues/360 but this time it is for MarkLogicConnection.remove()

The query is again built the wrong way so that only does statements are deleted that appear in all the specified contexts.

**Comment by elky87** [comment]
The fix I pushed is a little bit of a hack because it transform one delete query into X different delete queries depending on the number of contexts used. Maybe you can find a better solution but I was not quite sure how the sparql managers set binding worked.

**Comment by elky87** [comment]
Tests run through but in production I get "Cannot execute multiple SPARQL Update statements with same-statement isolation" so this fix is not a real fix.

**Comment by grechaw** [comment]
Hi @elky87 , this issue's fix has been merged into the rdf4j develop branch. Thanks for your help getting it reported and addressed. I'll close this one out as part of our cleanup of this repository.
We don't intend to fix this bug in the marklogic-sesame project.
