### ISSUE TITLE
Has statement cannot handle BNodes

### ISSUE THREAD

**Issue by elky87** [marklogic/marklogic-sesame#364]
try 

Bnode somenode = SimpleValueFactory.getInstance().createBNode();
hasStatement(null, null, somenode, false)

Error message: "BNode references not supported by SPARQL end-points"

**Comment by akshaysonvane** [comment]
Hi @elky, for BNode, when we persist the BNode on file or in DB we can not query the same BNode, once we re-run the program. As on each run a new BNode will be generated which will not match the one that was persisted before in the database.

```
File dataDir = new File(“somepath”);
Repository db = new SailRepository(new MemoryStore(dataDir));
db.initialize();

try (RepositoryConnection conn = db.getConnection()) {
            ValueFactory vf = conn.getValueFactory();
            Resource context1 = vf.createIRI("http://marklogic.com/test/context1");
            IRI alice = vf.createIRI("http://example.org/people/alice");
            IRI name = vf.createIRI("http://example.org/ontology/name");
            BNode alicesName = vf.createBNode();
            Statement st1 = vf.createStatement(alice, name, alicesName);
            conn.add(st1, context1);
            System.out.println(conn.hasStatement(null, null, alicesName, false));

            BNode markName = vf.createBNode();
            System.out.println(conn.hasStatement(null, null, markName, false));
        }
        finally {
            db.shutDown();
        }
```
When we re-run the above code to check for the persisted aliceName BNode, we wont be able to find it.
For more information: https://github.com/marklogic/marklogic-rdf4j/pull/12

**Comment by elky87** [comment]
Hi @akshaysonvane , thanks I am aware of this behaviour of BNodes. 

My example above was not complete enough, I apologize. We use BNodes in the following way:

First we create a BNode and use it for our purpose via:

    BNode alicesName = vf.createBNode();

Then we save the id of this Bnode for later use with:
  
    String bNodeIdFromAlicesName = alicesName.getId();

And in some later part we want to check, if this BNode is still there. We do this via:

    BNode alicesName = vf.createBNode(bNodeIdFromAlicesName);
    conn.hasStatement(null, null, alicesName, false);

So as long as this use case works, we are fine with that.

**Comment by grechaw** [comment]
Well, @akshaysonvane and I just learned something today :)

It looks like, since we also use a deterministic method to create skolemized bnodes, that this behavior is simple to support and Akshay is digging into it.

**Comment by akshaysonvane** [comment]
Hi @elky87, this issue's fix has been merged into the rdf4j develop branch. https://github.com/akshaysonvane/marklogic-rdf4j/commit/33e562e68e36b607c35a0e945f9f649c7a14504d Thanks for your help getting it reported and addressed. I'll close this one out as part of our cleanup of this repository.
We don't intend to fix this bug in the marklogic-sesame project.

**Comment by elky87** [comment]
Hi, just found a little additional info to skolemization of bnodes, maybe thats interesting for you https://www.w3.org/TR/rdf11-concepts/#section-skolemization

**Comment by grechaw** [comment]
Hi @elky87 , indeed, the internal format of skolemized ids conforms more-or-less to the spirit of that spec. basically they are of the form `http://marklogic.com/semantics/blank/{id}`  The id for us is an unsigned integer rather than a guid, however.
