### ISSUE TITLE
Bnodes handling is wrong and can cause data corruption

### ISSUE THREAD

**Issue by RavinderSinghMaan** [marklogic/marklogic-sesame#365]
In TripleWriteCache.java blank nodes are converted to IRI. Which means if blank node ids are not globally unique subsequent writes will add triples using same IRIs. This means if you are using RDF lists or blank nodes DESCRIBE queries will start to returning corrupt results.

**Comment by grechaw** [comment]
Hi @RavinderSinghMaan , normally we use large random numbers to ensure uniqueness of the skolemized IRIs, with possibility of collisions being extremely low.

If you have a bug that we can reproduce, please open an issue in the replacement project, marklogic-rdf4j.  We are not planning any more fixes or releases in this project.

**Comment by RavinderSinghMaan** [comment]
Hi @grechaw , just had a look at rdf4j and it seems the same problem exist there as well. So in TripleWriteCache.java there is if statements which converts BNodes to IRI. See the line from TripleWriteCache.java below
                        `entireQuery.append("<http://marklogic.com/semantics/blank/" + stmt.getSubject().stringValue() + "> ");`

And if I run below test

`    @Test
    public void name() throws Exception {
        final LinkedHashModel statements = new LinkedHashModel();
        statements.add(new BNodeImpl("_:b12"), new URIImpl("urn:pred"), new URIImpl("urn:obj"), new URIImpl("urn:graph"));
        conn.begin();
        conn.add(statements);
        conn.commit();
    }
`
In ML I end up getting

`<sem:triples xmlns:sem="http://marklogic.com/semantics">
<sem:triple>
<sem:subject>http://marklogic.com/semantics/blank/_:b12</sem:subject>
<sem:predicate>urn:pred</sem:predicate>
<sem:object>urn:obj</sem:object>
</sem:triple>
</sem:triples>`

Point here is that internally sesame-library generate below SPARQL UPDATE for above test

`INSERT DATA {  GRAPH <urn:graph> { <http://marklogic.com/semantics/blank/_:b12> <urn:pred> <urn:obj> . }} `

As you can see blank nodes has already been converted to IRI when the query goes to ML it won't generate unique id for blank node.

Thanks
Ravinder

**Comment by grechaw** [comment]
Hi @RavinderSinghMaan , i was able to verify the same thing.    Thanks for the code.

Ironically, it was one of your colleagues who showed us this behavior before, and required it to act deterministic  wrt ids in exactly this way.

What is the purpose of  "_b12" in new BNodeImpl("_:b12").   According to your colleague (I don't remember with whom I discussed this), the purpose of this function is to recreate BNodes identical to previous runs -- a use case that surprised me at the time.

There are two functions for createing bnodes, one for deterministic ones, and one for random ones.  the BNodeImpl () is deprecated in rdf4j -- this is how:

rep.getValueFactory().createBNode();

You will get a newly minted one each time this way.

**Comment by RavinderSinghMaan** [comment]
Hi @grechaw , I am not sure who discussed it. Maybe various concepts are being mixed here. But the point I am trying to make is that SPARQL INSERT statement which is generated by marklogic-sesame, should not convert blank nodes to IRIs because SPARQL engine in MarkLogic will take care of that. In other words instead of doing this `entireQuery.append("<http://marklogic.com/semantics/blank/" + stmt.getSubject().stringValue() + "> ");` in TripleWriteCache.java,  it should be `entireQuery.append("_:" + stmt.getSubject().stringValue() + " ");`

**Comment by akshaysonvane** [comment]
Hi @RavinderSinghMaan,
As BNode references are not supported by SPARQL end-points we need to convert them to IRI's in order to query them. https://github.com/marklogic/marklogic-sesame/issues/364

While creating a BNode 
```
rep.getValueFactory().createBNode(); 
```
should be used which generates a unique identifier for the BNode. (It creates a BNode based on currentTimeMillis(). Combined with a sequential number per session, which gives a unique identifier.)

Now if we require the ID of the BNode we can use "getId()" as follows:
```
BNode alicesName = vf.createBNode();
String bNodeIdFromAlicesName = alicesName.getId(); 
```
This workflow assures for the most part that the identifiers will tend to be unique.

But if we are providing an Id using 
```
vf.createBNode("b12");
```
then it becomes our responsibility to provide a unique Id.

**Comment by grechaw** [comment]
I'm going to close this issue as part of marklogic-sesame cleanup, and as we feel the bnode handling in this case is intentional.
