### ISSUE TITLE
update examples subproject

### ISSUE THREAD

**Issue by xquery** [marklogic/marklogic-sesame#40]
example subproject should be updated to; 

* illustrate how to use marklogic-sesame-repisotory as a gradle dependency 
* provide code examples 'in situ'. 
* links to relevant javadocs

**Comment by xquery** [comment]
https://github.com/marklogic/marklogic-sesame/tree/develop/marklogic-sesame-examples

**Comment by srinathgit** [comment]
Jim,

I just want to point out that there are no links to relevant javadocs in the examples sub project. Please add them if necessary , apart from that , it looks fine.

**Comment by xquery** [comment]
thanks for reviewing, note that the top level README has such links so I am not going to duplicate them here.
