### ISSUE TITLE
con.prepareGraphQuery(QueryLanguage.SPARQL, String query, String baseuri)  and con.prepareUpdateQuery(QueryLanguage.SPARQL, String query, String baseuri) doesn't work with baseURI

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#45]
On evaluating the query obtained by prepareGraphQuery  and prepareUpdateQuery method when used with a baseuri doesn't give the correct result and always returns empty result set.

**Comment by xquery** [comment]
fixed

**Comment by srinathgit** [comment]
prepare*Query() don't work with empty base uri's
testAdminCon.prepareBooleanQuery(QueryLanguage.SPARQL, query1,"")

**Comment by xquery** [comment]
ok, I fixed just the add w/ statements case ... looks like coercing the streams are going to require a different codepath.

**Comment by xquery** [comment]
I've added some more logic for excluding BASE if defined as "" ... though if relative URIs are returned in the resultant query and an invalid base URI was never declared we will get an error. I believe that is the current plan of record for this behavior as Sesame will not parse result set.

Furthermore, we need to decide if adding via File if we should default to File URI. I will add that as a new issue.

**Comment by srinathgit** [comment]
con.prepareGraphQuery(QueryLanguage.SPARQL, String query, String baseuri) and con.prepareUpdateQuery(QueryLanguage.SPARQL, String query, String baseuri) work with baseURI and also for cases when baseURI is empty
