### ISSUE TITLE
Handling different input conditions in query.evaluate(int, int) 

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#71]
1. For the method query.evaluate (int, int), if either start or pageLength or both are negative, the entire result set is returned. Is that an expected behavior  or should an error be thrown ?

2. Also if pageLength is out of bounds (as in size of result set is 10, start is 8 and pageLength is 5), results 8, 9 and 10 are returned with no errors thrown. IS that an expected behavior as well ?

**Comment by xquery** [comment]
yes these are both 'as expected' behavior defined by ML server, closing.

**Comment by srinathgit** [comment]
I think I made a mistake in the description above . Just to clarify, the behavior is as follows:

query.evaluate(-2,3), result sets 1, 2, 3 are returned
query.evaluate(3,-5), result sets 3,4..... till end of results are returned
query.evaluate(-5,-5) returns the entire result set.

Please correct me if I am wrong .

**Comment by xquery** [comment]
Yes, all expected as defined by ML Server.
