### ISSUE TITLE
User with only 'rest-reader' role able to execute update statements

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#84]
1. A user 'reader' with 'rest-reader', 'rest-extension-user' roles was created.
2. testReaderRepository = new MarkLogicRepository("localhost", restPort, "reader", "reader", "DIGEST");
testReaderRepository.initialize();
testReaderCon = (MarkLogicRepositoryConnection) testReaderRepository.getConnection();
3. testReaderCon.prepareUpdate("CREATE GRAPH <abc>").execute(); creates a graph <abc> which is not expected as the user doesn't have rest-writer role.

**Comment by xquery** [comment]
I tested REST endpoint with a user with rest-extension-user and rest-reader role.

```
curl --anyauth --user reader:reader -i -X POST -H "Content-type:application/x-www-form-urlencoded" -H "Accept:application/sparql-results+xml" --data-urlencode update='PREFIX dc: <http://purl.org/dc/elements/1.1/> INSERT DATA{ GRAPH <C1> {<http://example/book1/> dc:title "C book"} }' 'http://localhost:8200/v1/graphs/sparql'
```
and this throws correct error.

I was unable to replicate in Sesame with

```
    @Test
    public void testCreateGraph() throws Exception
    {
        conn.prepareUpdate("CREATE GRAPH <http://example1.org>").execute();
    }
```

using the same user.

**Comment by srinathgit** [comment]
I think I understand the issue now. The code snippet I used to create MarkLogicRepositoryConnection objects using 'reader' and 'writer' user ('reader' user has rest-extension-user and rest-reader role and writer user has rest-extension-user ,rest-reader and rest-writer role ) is as follows:

testReaderRepository = new MarkLogicRepository("localhost", restPort, "reader", "reader", "DIGEST");
try {
	testReaderRepository.initialize();
	testReaderCon = (MarkLogicRepositoryConnection) testReaderRepository.getConnection();
} catch (RepositoryException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}
=>  testReaderCon.prepareUpdate("CREATE GRAPH <abc>").execute();
//Creating MLSesame Connection object Using MarkLogicRepository(databaseclient)  constructor

DatabaseClient databaseClient = DatabaseClientFactory.newClient("localhost", restPort, "writer", "writer", DatabaseClientFactory.Authentication.valueOf("DIGEST"));
testWriterRepository = new MarkLogicRepository(databaseClient);

try {
	testWriterRepository.initialize();
	testWriterCon = (MarkLogicRepositoryConnection) testWriterRepository.getConnection();
} catch (RepositoryException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}
=>  testReaderCon.prepareUpdate("CREATE GRAPH <abcdef>").execute();

The first update statement " testReaderCon.prepareUpdate("CREATE GRAPH <abc>").execute();"
fails as the statement is executed using 'reader' user.

The second update statement (executed after creating 'testWriterCon') "testReaderCon.prepareUpdate("CREATE GRAPH <abcdef>").execute();" succeeds as the statement is executed using 'writer'. Now the question is  why 'writer' user is used for executing the update statement even though the method is called on testReaderCon object

**Comment by xquery** [comment]
ok that points to some kind of unwanted singleton behavior ... will sort out today.

**Comment by srinathgit** [comment]
Verified that the singleton issue has been fixed .
