### ISSUE TITLE
con.size() returning incorrect results

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#86]
con.size() is expected to return the number of triples in the entire db (triples with or without contexts). But the result returned is incorrect. Upon checking 'MarkLogicTupleQuery.java', the value of pagelength has been hardcoded to 50 and all select queries now return only a maximum of 50 results.

**Comment by xquery** [comment]
this is a holding position ... waiting for resolution of this deeper in the stack (java api client) ... I will increase to 100000 for now.

**Comment by xquery** [comment]
pls test and hand back to me ... I will remove hardcoded constant once java api client has changed

**Comment by srinathgit** [comment]
con.size() is working now. Reassigning back to Jim to remove hardcoded constant once java client api is changed.

**Comment by gvaidees** [comment]
I am assigning this to Charles so that he can fix it when Java API is fixed

**Comment by srinathgit** [comment]
waiting on bug 34901

**Comment by srinathgit** [comment]
con.size() works fine.
