### ISSUE TITLE
Unable to select triples inserted from Query console

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#91]
The triples inserted from query console are not returned using 'SELECT' query from within Sesame.

Steps:
1. Run INSERT DATA { GRAPH <http://abcd> {<abc> <sdf> "fbefbj".} } in Queryconsole.
2. URI ur = vf.createURI("http://abcd");
logger.debug("Size of abcd is"+ testAdminCon.size(ur));

returns the size as zero. The query executed from Sesame is "SELECT * WHERE { GRAPH <http://abcd> {?s ?p ?o .} }"  returns an empty result set but which as expected returns the result set when run from Query console.

**Comment by xquery** [comment]
Triples added via qconsole have no perms applied to them (assuming you are logged in as admin).

Triples added via Sesame are loaded via java api client which leverages the REST api and thusly applies minimal rest role perms.

I agree that this behavior is confusing but it is correct.

**Comment by srinathgit** [comment]
The users used in both cases are 'admin' user. I used admin user to log into qconsole and creatr triples. Also I used the same admin user in marklogic-sesame to obtain the MarkLogicRepositoryConnection object.

**Comment by xquery** [comment]
Yes I think I understand. 

You will not get same behavior from REST API and qconsole using admin user ... everything going through REST API will minimally require these perms. This is as designed and there is no way for us (currently) to make Sesame add triples (via REST api) with no perms.

**Comment by srinathgit** [comment]
Shipping this bug as triples created using Qconsole don't have necessary permissions which are required to access from Sesame (using rest api).

**Comment by grechaw** [comment]
+1

**Comment by srinathgit** [comment]
Charles,

As we discussed , I see that I cannot read the triples created in Qconsole from within marklogic-sesame application (using 'admin' user in both Qconsole and sesame application) because the documents don't have necessary permissions but when I call the method con.clear() from withn sesame, it clears all the documents irrespective of whether they were created in Qconsole or from sesame. Is this expected behavior ?

**Comment by grechaw** [comment]
No, I think there's something wrong in sesame.    What's the test?  If you are connecting with admin, I'd expect you should be able to see all the triples, even over REST.  It might be that the sesame is using a less privileged connection than it should.

**Comment by srinathgit** [comment]
I am not sure what changed but now when I create a triple in QConsole, I am able to see them from within marklogic-sesame

**Comment by xquery** [comment]
and me too ... is this now a non bug ?

**Comment by srinathgit** [comment]
Closing this as it is not a bug
